### ISSUE TITLE
Bug: return false when case is safe

### ISSUE THREAD

**Issue by Gary-oak-Star** [gipsyh/rIC3#2]
[test.txt](https://github.com/gipsyh/ic3/files/13692061/test.txt)

This case should be safe (has already been verified by other model checkers) but in this model checker returns false. It indicates that there is some bug in the implementation (rename to .aag and it should be ok to run)

The output in terminal

<img width="425" alt="image" src="https://github.com/gipsyh/ic3/assets/120406793/910c5047-e5f4-4deb-af91-ff087fb6e5c0">

**Comment by gipsyh** [comment]
This checker currently does not support constraints. Contributions are welcome!
<img width="330" alt="截屏2023-12-16 18 01 17" src="https://github.com/gipsyh/ic3/assets/42509521/2d80a1ce-9571-4c97-b660-157b148b9d9d">
this case has 9 constraints, which are ignored by this model checker.

**Comment by gipsyh** [comment]
Thanks.

Actually, it is competitive with ic3ref as tested in hwmcc15 and 17. It can even solve more cases than ic3ref.

**Comment by gipsyh** [comment]
In terms of implementation, many parts were borrowed from ic3ref.
